/**
 * Emit the Tailwind v4 `@theme` block to `dist/theme.css` from tokens.json.
 * The web app imports the generated file so its utilities stay in lockstep with
 * the single source of truth. Run via `pnpm --filter @stoliq/ui-tokens build`.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { themeCss } from '../src/index';

const here = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(here, '../dist/theme.css');

const banner = `/* GENERATED by @stoliq/ui-tokens — do not edit. Source: tokens.json */\n`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, banner + themeCss(), 'utf8');

console.log(`ui-tokens: wrote ${outPath}`);
